### ISSUE TITLE
Quasar 0.17.0 or 0.17.1 doesn't works

### ISSUE THREAD

**Issue by uno-de-piera** [quasarframework/quasar-cli#153]
Hi,

Today I updated a old project to Quasar 0.17.1, when I tried to start the application crashes with multiple errors and warnings.

With 0.16.0 works fine after update, now doesn't works with any version, I tested in different machines after update to 0.17.1 with same result :(

Quasar Info

```
Operating System         	Darwin(16.7.0) - darwin/x64
NodeJs                   	9.11.1

Global packages
  NPM                    	5.6.0
  yarn                   	1.7.0
  quasar-cli             	0.17.1
  vue-cli                	2.9.6
  cordova                	7.1.0

Important local packages
  quasar-cli             	0.17.1	(Quasar Framework CLI)
  quasar-framework       	0.17.1	(Build responsive websites, PWAs, hybrid mobile apps and Electron apps, all simultaneously using same codebase)
  quasar-extras          	2.0.4	(Quasar Framework fonts, icons and animations)
  vue                    	2.5.16	(Reactive, component-oriented view layer for modern web interfaces.)
  vue-router             	3.0.1	(Official router for Vue.js 2)
  vuex                   	3.0.1	(state management for Vue.js)
  electron               	Not installed
  electron-packager      	Not installed
  electron-builder       	Not installed
  @babel/core            	7.0.0-beta.54	(Babel compiler core.)
  webpack                	4.16.2	(Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server     	3.1.5	(Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin 	3.4.1	(A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
  register-service-worker	1.4.1	(Script for registering service worker, with hooks)

Networking
  Host                   	iMac.local
  en1                    	192.168.1.41
  vboxnet0               	192.168.56.1
```

```
quasar dev -m cordova -T android

 Dev mode.......... cordova
 Quasar theme...... mat
 Quasar CLI........ v0.17.1
 Quasar Framework.. v0.17.1
 Debugging......... enabled

 app:mode Quasar CORDOVA is missing. Installing it... +0ms
 app:mode-cordova Creating Cordova source folder... +1ms
 app:spawn [sync] Running "cordova create src-cordova mobile.app.es Quasar App" +0ms

Creating a new cordova project.
 app:mode-cordova Cordova support was installed +10s
 app:mode-cordova App name was taken from package.json: "Quasar App" +0ms

 app:mode-cordova If you want a different App name then remove Cordova support, edit productName field from package.json then add Cordova support again. +0ms

 app:mode-cordova Adding Cordova platform "android" +1ms
 app:spawn [sync] Running "cordova platform add android" +0ms

Using cordova-fetch for cordova-android@~6.3.0
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: mobile.app..es
	Name: Quasar_App
	Activity: MainActivity
	Android target: android-26
Subproject Path: CordovaLib
Android project created with cordova-android@6.3.0
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.

Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
--save flag or autosave detected
Saving android@~6.3.0 into config.xml file ...
 app:quasar-conf Reading quasar.conf.js +14s
? What external IP should Quasar use? 192.168.1.41
 app:dev Checking listening address availability (192.168.1.41:8080)... +2s
 app:webpack Extending Cordova Webpack config +318ms
 app:generator Generating Webpack entry point +33ms
 app:dev-server Booting up... +2ms


  Cordova █████████████████████████ [100%] in ~12s



 ERROR  Failed to compile with 1 errors                                 09:50:03

 error


✖ ｢wdm｣: Hash: bfd59f46200a52eb1108
Version: webpack 4.16.2
Time: 11914ms
Built at: 2018-07-26 09:50:03
                                         Asset      Size  Chunks                    Chunk Names
               fonts/KFOmCnqEu92Fr1Mu4mxM.woff  19.4 KiB          [emitted]
       fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNa.woff  62.5 KiB          [emitted]
            fonts/KFOkCnqEu92Fr1MmgVxIIzQ.woff  19.5 KiB          [emitted]
           fonts/KFOlCnqEu92Fr1MmEU9fBBc-.woff  19.5 KiB          [emitted]
           fonts/KFOlCnqEu92Fr1MmSU5fBBc-.woff  19.4 KiB          [emitted]
           fonts/KFOlCnqEu92Fr1MmWUlfBBc-.woff  19.4 KiB          [emitted]
           fonts/KFOlCnqEu92Fr1MmYUtfBBc-.woff  19.5 KiB          [emitted]
fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2    48 KiB          [emitted]
                      img/quasar-logo-full.svg  12.6 KiB          [emitted]
                                        app.js  4.07 MiB     app  [emitted]  [big]  app
                                          0.js  47.9 KiB       0  [emitted]
                                          1.js  29.8 KiB       1  [emitted]
                                          2.js  43.4 KiB       2  [emitted]
                                    index.html  1.38 KiB          [emitted]
Entrypoint app [big] = app.js
[./.quasar/app.js] 608 bytes {app} [built]
[./.quasar/client-entry.js] 617 bytes {app} [built]
[./node_modules/strip-ansi/index.js] 208 bytes {app} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 746 bytes {app} [built]
[0] multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js 52 bytes {app} [built]
[./node_modules/url/url.js] 15.6 KiB {app} [built]
[./node_modules/vue/dist/vue.runtime.esm.js] 163 KiB {app} [built]
[./node_modules/webpack-dev-server/client/index.js?http://192.168.1.41:8080] (webpack)-dev-server/client?http://192.168.1.41:8080 6.33 KiB {app} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 2.64 KiB {app} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {app} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.51 KiB {app} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {app} [built]
[./node_modules/webpack/hot/log-apply-result.js] (webpack)/hot/log-apply-result.js 1.3 KiB {app} [built]
[./node_modules/webpack/hot/log.js] (webpack)/hot/log.js 1 KiB {app} [built]
[./src/css/app.styl] 1.38 KiB {app} [built]
    + 349 hidden modules

WARNING in ./node_modules/quasar-framework/src/plugins/platform.js 166:8-21
"export 'default' (imported as '_objectSpread') was not found in '@babel/runtime/helpers/objectSpread'
 @ ./node_modules/quasar-framework/src/components/layout/QLayout.js
 @ ./.quasar/import-quasar.js
 @ ./.quasar/app.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/sockjs-client/dist/sockjs.js 4419:34-41
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client/socket.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/vue/dist/vue.runtime.esm.js 44:25-32
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/vue/dist/vue.runtime.esm.js 67:28-35
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/vue/dist/vue.runtime.esm.js 1261:12-19
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/vue/dist/vue.runtime.esm.js 5726:6-13
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/events/events.js 215:9-16
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)/hot/emitter.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/url/util.js 9:11-18
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./node_modules/url/url.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/node-libs-browser/node_modules/punycode/punycode.js 7:68-75
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./node_modules/url/url.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/node-libs-browser/node_modules/punycode/punycode.js 8:66-73
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./node_modules/url/url.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/node-libs-browser/node_modules/punycode/punycode.js 9:66-73
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./node_modules/url/url.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/node-libs-browser/node_modules/punycode/punycode.js 329:37-44
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./node_modules/url/url.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/core-js/library/modules/_is-object.js 4:9-16
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./node_modules/core-js/library/modules/es6.symbol.js
 @ ./node_modules/core-js/library/fn/symbol/index.js
 @ ./node_modules/@babel/runtime/core-js/symbol.js
 @ ./node_modules/@babel/runtime/helpers/typeof.js
 @ ./node_modules/url/url.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/core-js/library/modules/_meta.js 33:28-35
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./node_modules/core-js/library/modules/es6.symbol.js
 @ ./node_modules/core-js/library/fn/symbol/index.js
 @ ./node_modules/@babel/runtime/core-js/symbol.js
 @ ./node_modules/@babel/runtime/helpers/typeof.js
 @ ./node_modules/url/url.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/core-js/library/modules/es6.symbol.js 98:9-16
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./node_modules/core-js/library/fn/symbol/index.js
 @ ./node_modules/@babel/runtime/core-js/symbol.js
 @ ./node_modules/@babel/runtime/helpers/typeof.js
 @ ./node_modules/url/url.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in (webpack)/buildin/global.js 11:53-60
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./node_modules/vue/dist/vue.runtime.esm.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/loglevel/lib/loglevel.js 8:60-67
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/loglevel/lib/loglevel.js 42:56-63
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/loglevel/lib/loglevel.js 64:58-65
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/loglevel/lib/loglevel.js 86:57-64
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/loglevel/lib/loglevel.js 100:57-64
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/loglevel/lib/loglevel.js 106:10-17
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/loglevel/lib/loglevel.js 153:60-67
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/loglevel/lib/loglevel.js 201:60-67
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/loglevel/lib/loglevel.js 204:55-62
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/sockjs-client/dist/sockjs.js 13:54-61
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client/socket.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/sockjs-client/dist/sockjs.js 1273:16-23
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client/socket.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/sockjs-client/dist/sockjs.js 3578:86-93
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client/socket.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/sockjs-client/dist/sockjs.js 3613:21-28
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client/socket.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/sockjs-client/dist/sockjs.js 3833:78-85
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client/socket.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/sockjs-client/dist/sockjs.js 4033:40-47
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client/socket.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/sockjs-client/dist/sockjs.js 4034:79-86
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client/socket.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/sockjs-client/dist/sockjs.js 4035:54-61
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client/socket.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/sockjs-client/dist/sockjs.js 4035:104-111
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client/socket.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/sockjs-client/dist/sockjs.js 4053:16-23
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client/socket.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/sockjs-client/dist/sockjs.js 4217:108-115
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client/socket.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/sockjs-client/dist/sockjs.js 4321:22-29
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client/socket.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/sockjs-client/dist/sockjs.js 4380:22-29
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client/socket.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/vue/dist/vue.runtime.esm.js 40:67-74
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/sockjs-client/dist/sockjs.js 4730:22-29
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client/socket.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/sockjs-client/dist/sockjs.js 4807:19-26
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client/socket.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/sockjs-client/dist/sockjs.js 5006:21-28
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client/socket.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/sockjs-client/dist/sockjs.js 5077:21-28
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client/socket.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/sockjs-client/dist/sockjs.js 5233:31-38
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client/socket.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/ansi-html/index.js 82:6-13
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client/overlay.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/core-js/modules/es6.symbol.js 97:29-36
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./node_modules/vue/dist/vue.runtime.esm.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/core-js/modules/es6.symbol.js 98:9-16
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./node_modules/vue/dist/vue.runtime.esm.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/querystring-es3/encode.js 10:10-17
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./node_modules/querystring-es3/index.js
 @ ./node_modules/url/url.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/querystring-es3/encode.js 33:6-13
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./node_modules/querystring-es3/index.js
 @ ./node_modules/url/url.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/vuex/dist/vuex.esm.js 67:25-32
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./src/store/index.js
 @ ./.quasar/app.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/vuex/dist/vuex.esm.js 237:42-49
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./src/store/index.js
 @ ./.quasar/app.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/vuex/dist/vuex.esm.js 748:80-87
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./src/store/index.js
 @ ./.quasar/app.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/vue-router/dist/vue-router.esm.js 118:10-17
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./src/router/index.js
 @ ./.quasar/app.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/vue-router/dist/vue-router.esm.js 133:62-69
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./src/router/index.js
 @ ./.quasar/app.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/vue-router/dist/vue-router.esm.js 270:22-29
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./src/router/index.js
 @ ./.quasar/app.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/vue-router/dist/vue-router.esm.js 341:8-15
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./src/router/index.js
 @ ./.quasar/app.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/vue-router/dist/vue-router.esm.js 341:38-45
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./src/router/index.js
 @ ./.quasar/app.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/vue-router/dist/vue-router.esm.js 716:8-15
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./src/router/index.js
 @ ./.quasar/app.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/vue-router/dist/vue-router.esm.js 1148:10-17
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./src/router/index.js
 @ ./.quasar/app.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/vue-router/dist/vue-router.esm.js 1152:26-33
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./src/router/index.js
 @ ./.quasar/app.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/vue-router/dist/vue-router.esm.js 1190:21-28
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./src/router/index.js
 @ ./.quasar/app.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/vue-router/dist/vue-router.esm.js 1404:17-24
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./src/router/index.js
 @ ./.quasar/app.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/vue-router/dist/vue-router.esm.js 1410:42-49
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./src/router/index.js
 @ ./.quasar/app.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/vue-router/dist/vue-router.esm.js 1564:48-55
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./src/router/index.js
 @ ./.quasar/app.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/vue-router/dist/vue-router.esm.js 1691:45-52
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./src/router/index.js
 @ ./.quasar/app.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/vue-router/dist/vue-router.esm.js 1694:14-21
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./src/router/index.js
 @ ./.quasar/app.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/url/url.js 79:67-74
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/core-js/modules/_is-object.js 4:9-16
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./node_modules/core-js/modules/es6.object.is-frozen.js
 @ ./node_modules/vue/dist/vue.runtime.esm.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/core-js/modules/_object-gopn-ext.js 9:65-72
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./node_modules/core-js/modules/es6.symbol.js
 @ ./node_modules/vue/dist/vue.runtime.esm.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/core-js/modules/_meta.js 33:28-35
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./node_modules/core-js/modules/es6.symbol.js
 @ ./node_modules/vue/dist/vue.runtime.esm.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/core-js/modules/_typed-array.js 328:54-61
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./node_modules/core-js/modules/es6.typed.uint8-array.js
 @ ./node_modules/sockjs-client/dist/sockjs.js
 @ (webpack)-dev-server/client/socket.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/core-js/library/modules/es6.symbol.js 97:29-36
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./node_modules/core-js/library/fn/symbol/index.js
 @ ./node_modules/@babel/runtime/core-js/symbol.js
 @ ./node_modules/@babel/runtime/helpers/typeof.js
 @ ./node_modules/url/url.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/core-js/library/modules/_object-gopn-ext.js 9:65-72
"export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
 @ ./node_modules/core-js/library/modules/es6.symbol.js
 @ ./node_modules/core-js/library/fn/symbol/index.js
 @ ./node_modules/@babel/runtime/core-js/symbol.js
 @ ./node_modules/@babel/runtime/helpers/typeof.js
 @ ./node_modules/url/url.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/@babel/runtime/helpers/typeof.js 14:123-131
"export 'default' (imported as '_typeof3') was not found in '@babel/runtime/helpers/typeof'
 @ ./node_modules/url/url.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/@babel/runtime/helpers/typeof.js 10:13-21
"export 'default' (imported as '_typeof3') was not found in '@babel/runtime/helpers/typeof'
 @ ./node_modules/url/url.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

WARNING in ./node_modules/@babel/runtime/helpers/typeof.js 8:39-47
"export 'default' (imported as '_typeof3') was not found in '@babel/runtime/helpers/typeof'
 @ ./node_modules/url/url.js
 @ (webpack)-dev-server/client?http://192.168.1.41:8080
 @ multi (webpack)-dev-server/client?http://192.168.1.41:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

ERROR in   Error: webpack-internal:///./node_modules/core-js/modules/_is-object.js:5
  module.exports = function (it) {
                 ^
  TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
  - _is-object.js:5 Module.eval
    [.]/[core-js]/modules/_is-object.js:5:16

  - _is-object.js:8 eval
    [.]/[core-js]/modules/_is-object.js:8:30

  - index.template.html:1767 Module../node_modules/core-js/modules/_is-object.js    /busca-quasar/src/index.template.html:1767:1
  - index.template.html:684 __webpack_require__
    /busca-quasar/src/index.template.html:684:30
  - index.template.html:61 fn
    /busca-quasar/src/index.template.html:61:20

  - _inherit-if-required.js:1 eval
    [.]/[core-js]/modules/_inherit-if-required.js:1:16

  - index.template.html:1743 Object../node_modules/core-js/modules/_inherit-if-r    equired.js
    /busca-quasar/src/index.template.html:1743:1
  - index.template.html:684 __webpack_require__
    /busca-quasar/src/index.template.html:684:30
  - index.template.html:61 fn
    /busca-quasar/src/index.template.html:61:20

  - es6.regexp.constructor.js:3 eval
    [.]/[core-js]/modules/es6.regexp.constructor.js:3:25


Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks  Chunk Names
    index.html  1.7 MiB       0
    Entrypoint undefined = index.html
    [./node_modules/@babel/runtime/core-js/symbol.js] 54 bytes {0} [built]
    [./node_modules/@babel/runtime/core-js/symbol/iterator.js] 63 bytes {0} [built]
    [./node_modules/@babel/runtime/helpers/typeof.js] 1.01 KiB {0} [built]
    [./node_modules/core-js/library/fn/symbol/index.js] 243 bytes {0} [built]
    [./node_modules/core-js/library/fn/symbol/iterator.js] 156 bytes {0} [built]
    [./node_modules/core-js/library/modules/_core.js] 91 bytes {0} [built]
    [./node_modules/core-js/library/modules/_wks-ext.js] 30 bytes {0} [built]
    [./node_modules/core-js/library/modules/es6.object.to-string.js] 0 bytes {0} [built]
    [./node_modules/core-js/library/modules/es6.string.iterator.js] 421 bytes {0} [built]
    [./node_modules/core-js/library/modules/web.dom.iterable.js] 1010 bytes {0} [built]
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.template.html] 1.26 KiB {0} [built]
    [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 297 bytes {0} [built]
    [./node_modules/webpack/buildin/harmony-module.js] (webpack)/buildin/harmony-module.js 590 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 511 bytes {0} [built]
        + 125 hidden modules

    WARNING in ./node_modules/core-js/library/modules/es6.symbol.js 97:29-36
    "export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
     @ ./node_modules/core-js/library/fn/symbol/index.js
     @ ./node_modules/@babel/runtime/core-js/symbol.js
     @ ./node_modules/@babel/runtime/helpers/typeof.js
     @ (webpack)/buildin/global.js
     @ ./node_modules/lodash/lodash.js
     @ ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.template.html

    WARNING in (webpack)/buildin/global.js 11:53-60
    "export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
     @ ./node_modules/lodash/lodash.js
     @ ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.template.html

    WARNING in ./node_modules/core-js/library/modules/_object-gopn-ext.js 9:65-72
    "export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
     @ ./node_modules/core-js/library/modules/es6.symbol.js
     @ ./node_modules/core-js/library/fn/symbol/index.js
     @ ./node_modules/@babel/runtime/core-js/symbol.js
     @ ./node_modules/@babel/runtime/helpers/typeof.js
     @ (webpack)/buildin/global.js
     @ ./node_modules/lodash/lodash.js
     @ ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.template.html

    WARNING in ./node_modules/core-js/library/modules/_is-object.js 4:9-16
    "export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
     @ ./node_modules/core-js/library/modules/es6.symbol.js
     @ ./node_modules/core-js/library/fn/symbol/index.js
     @ ./node_modules/@babel/runtime/core-js/symbol.js
     @ ./node_modules/@babel/runtime/helpers/typeof.js
     @ (webpack)/buildin/global.js
     @ ./node_modules/lodash/lodash.js
     @ ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.template.html

    WARNING in ./node_modules/core-js/modules/_is-object.js 4:9-16
    "export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
     @ ./node_modules/core-js/modules/_is-regexp.js
     @ ./node_modules/core-js/modules/es6.regexp.split.js
     @ ./node_modules/core-js/library/modules/web.dom.iterable.js
     @ ./node_modules/core-js/library/fn/symbol/iterator.js
     @ ./node_modules/@babel/runtime/core-js/symbol/iterator.js
     @ ./node_modules/@babel/runtime/helpers/typeof.js
     @ (webpack)/buildin/global.js
     @ ./node_modules/lodash/lodash.js
     @ ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.template.html

    WARNING in ./node_modules/core-js/library/modules/_meta.js 33:28-35
    "export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
     @ ./node_modules/core-js/library/modules/es6.symbol.js
     @ ./node_modules/core-js/library/fn/symbol/index.js
     @ ./node_modules/@babel/runtime/core-js/symbol.js
     @ ./node_modules/@babel/runtime/helpers/typeof.js
     @ (webpack)/buildin/global.js
     @ ./node_modules/lodash/lodash.js
     @ ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.template.html

    WARNING in ./node_modules/core-js/library/modules/es6.symbol.js 98:9-16
    "export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
     @ ./node_modules/core-js/library/fn/symbol/index.js
     @ ./node_modules/@babel/runtime/core-js/symbol.js
     @ ./node_modules/@babel/runtime/helpers/typeof.js
     @ (webpack)/buildin/global.js
     @ ./node_modules/lodash/lodash.js
     @ ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.template.html

    WARNING in ./node_modules/core-js/modules/_meta.js 33:28-35
    "export 'default' (imported as '_typeof') was not found in '@babel/runtime/helpers/typeof'
     @ ./node_modules/core-js/modules/es6.object.prevent-extensions.js
     @ ./node_modules/core-js/library/modules/_meta.js
     @ ./node_modules/core-js/library/modules/es6.symbol.js
     @ ./node_modules/core-js/library/fn/symbol/index.js
     @ ./node_modules/@babel/runtime/core-js/symbol.js
     @ ./node_modules/@babel/runtime/helpers/typeof.js
     @ (webpack)/buildin/global.js
     @ ./node_modules/lodash/lodash.js
     @ ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.template.html

    WARNING in ./node_modules/@babel/runtime/helpers/typeof.js 8:39-47
    "export 'default' (imported as '_typeof3') was not found in '@babel/runtime/helpers/typeof'
     @ (webpack)/buildin/global.js
     @ ./node_modules/lodash/lodash.js
     @ ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.template.html

    WARNING in ./node_modules/@babel/runtime/helpers/typeof.js 14:123-131
    "export 'default' (imported as '_typeof3') was not found in '@babel/runtime/helpers/typeof'
     @ (webpack)/buildin/global.js
     @ ./node_modules/lodash/lodash.js
     @ ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.template.html

    WARNING in ./node_modules/@babel/runtime/helpers/typeof.js 10:13-21
    "export 'default' (imported as '_typeof3') was not found in '@babel/runtime/helpers/typeof'
     @ (webpack)/buildin/global.js
     @ ./node_modules/lodash/lodash.js
     @ ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.template.html
```

**Comment by dlopezp** [comment]
Same erroe here, but with spa mode.

Quasar info:
`Operating System         	Darwin(17.7.0) - darwin/x64
NodeJs                   	10.2.1

Global packages
  NPM                    	5.6.0
  yarn                   	Not installed
  quasar-cli             	0.17.1
  vue-cli                	Not installed
  cordova                	Not installed

Important local packages
  quasar-cli             	0.17.1	(Quasar Framework CLI)
  quasar-framework       	0.17.1	(Build responsive websites, PWAs, hybrid mobile apps and Electron apps, all simultaneously using same codebase)
  quasar-extras          	2.0.4	(Quasar Framework fonts, icons and animations)
  vue                    	2.5.16	(Reactive, component-oriented view layer for modern web interfaces.)
  vue-router             	3.0.1	(Official router for Vue.js 2)
  vuex                   	3.0.1	(state management for Vue.js)
  electron               	Not installed
  electron-packager      	Not installed
  electron-builder       	Not installed
  @babel/core            	7.0.0-beta.54	(Babel compiler core.)
  webpack                	4.16.2	(Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server     	3.1.5	(Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin 	3.4.1	(A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
  register-service-worker	1.4.1	(Script for registering service worker, with hooks)

Networking
  Host                   	dani-cc
  en4                    	192.168.1.133`

**Comment by dlopezp** [comment]
Solved with quasar-cli 0.17.2, thx @rstoenescu !

**Comment by rstoenescu** [comment]
@uno-de-piera Does your problem get solved with v0.17.2 too? I see "ERROR  Failed to compile with 1 errors" in your copy-paste, and that only happens when there's a wrong dynamic import() in your code (path of import is wrong). Wish Webpack would offer more details on the exact import() causing trouble, but currently it outputs only that error.

**Comment by uno-de-piera** [comment]
@rstoenescu thanks for your quick reply, but the issue persist

```
➜  quasar17-2 quasar info

Operating System         	Darwin(16.7.0) - darwin/x64
NodeJs                   	9.11.1

Global packages          	
  NPM                    	5.6.0
  yarn                   	1.7.0
  quasar-cli             	0.17.2
  vue-cli                	2.9.6
  cordova                	8.0.0

Important local packages 	
  quasar-cli             	0.17.2	(Quasar Framework CLI)
  quasar-framework       	0.17.2	(Build responsive websites, PWAs, hybrid mobile apps and Electron apps, all simultaneously using same codebase)
  quasar-extras          	2.0.4	(Quasar Framework fonts, icons and animations)
  vue                    	2.5.16	(Reactive, component-oriented view layer for modern web interfaces.)
  vue-router             	3.0.1	(Official router for Vue.js 2)
  vuex                   	3.0.1	(state management for Vue.js)
  electron               	Not installed
  electron-packager      	Not installed
  electron-builder       	Not installed
  @babel/core            	7.0.0-beta.54	(Babel compiler core.)
  webpack                	4.16.2	(Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server     	3.1.5	(Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin 	3.4.1	(A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
  register-service-worker	1.4.1	(Script for registering service worker, with hooks)

Networking               	
  Host                   	MacBook-Pro-de-Israel.local
  en1                    	192.168.1.39
  vboxnet0               	192.168.56.1
```
And the same error
```
ERROR in   Error: webpack-internal:///./node_modules/core-js/modules/_is-object.js:5
  module.exports = function (it) {
                 ^
  TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
  
  - _is-object.js:5 Module.eval
    [.]/[core-js]/modules/_is-object.js:5:16
  
  - _is-object.js:8 eval
    [.]/[core-js]/modules/_is-object.js:8:30
  
  - index.template.html:1767 Module../node_modules/core-js/modules/_is-object.js
    /Users/iparra/tutorials/quasar/quasar17-2/src/index.template.html:1767:1
  
  - index.template.html:684 __webpack_require__
    /Users/iparra/tutorials/quasar/quasar17-2/src/index.template.html:684:30
  
  - index.template.html:61 fn
    /Users/iparra/tutorials/quasar/quasar17-2/src/index.template.html:61:20
  
  - _inherit-if-required.js:1 eval
    [.]/[core-js]/modules/_inherit-if-required.js:1:16
  
  - index.template.html:1743 Object../node_modules/core-js/modules/_inherit-if-required.js
    /Users/iparra/tutorials/quasar/quasar17-2/src/index.template.html:1743:1
  
  - index.template.html:684 __webpack_require__
    /Users/iparra/tutorials/quasar/quasar17-2/src/index.template.html:684:30
  
  - index.template.html:61 fn
    /Users/iparra/tutorials/quasar/quasar17-2/src/index.template.html:61:20
  
  - es6.regexp.constructor.js:3 eval
    [.]/[core-js]/modules/es6.regexp.constructor.js:3:25
```
Yesterday everything worked fine in my two computers :( with the same environment.
