### ISSUE TITLE
Does not recognize .npmrc configs with self-signed certificates or http proxies #346

### ISSUE THREAD

**Issue by rstoenescu** [quasarframework/quasar-cli#17]
Referencing https://github.com/quasarframework/quasar/issues/346

**Comment by klauern** [comment]
More as a brainstorming, but I was looking similarly for something like this with `yarn`, and found that they pull in the `.npmrc`, likely from this pull request: https://github.com/yarnpkg/yarn/pull/594

**Comment by rstoenescu** [comment]
This should be fixed with v0.5.1

**Comment by aldanor** [comment]
Still a problem with 0.6.4:

```
$ quasar-cli init default foo
Failed to download App template @quasarframework/quasar-template-default: RequestError: self signed certificate in certificate chain
```

```
$ quasar list
✖ Could not retrieve App starter kit: [object Object]
```

My `~/.npmrc` is like this:

```ini
proxy=http://...
https-proxy=http://...
strict-ssl=false
```

**Comment by rstoenescu** [comment]
Let's continue on the new thread #38
